

service: serverless-library-app

custom:
  settings:
    BOOKS_TABLE: books

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom.settings}
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamoDB:DescribeTable
        - dynamoDB:Scan
        - dynamoDB:GetItem
        - dynamoDB:PutItem
        - dynamoDB:UpdateItem
        - dynamoDB:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.BOOKS_TABLE}"


functions:
  createBook:
    handler: handler.createBook
    events:
      - http:
          path: /books/add
          method: post
  deleteBook:
    handler: handler.deleteBook
    events:
      - http:
          path: /book/{bookUuid}/delete
          method: post
  getBooks:
    handler: handler.getBooks
    events:
      - http:
          path: /books
          method: get
  getBook:
    handler: handler.getBook
    events:
      - http:
          path: /book/{bookUuid}
          method: get

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "uuid"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "uuid"
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        TableName: ${self:custom.settings.BOOKS_TABLE}


